"""initial migration

Revision ID: f7e958f1480c
Revises: 
Create Date: 2026-02-11 11:48:07.574683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e958f1480c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pantry--ingredient')
    op.drop_table('pantry--recipe_ingredient_assoc')
    op.drop_table('second_thought--justification')
    op.drop_table('pantry--recipe')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry--recipe',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('notes', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('second_thought--justification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ts', sa.DATETIME(), nullable=False),
    sa.Column('domain', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('reason', sa.VARCHAR(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pantry--recipe_ingredient_assoc',
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['pantry--ingredient.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['pantry--recipe.id'], ),
    sa.UniqueConstraint('recipe_id', 'ingredient_id', name=op.f('uq_recipe_ingredient'))
    )
    op.create_table('pantry--ingredient',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
