"""add_goal_history_tracking

Revision ID: 15c85a88b1c2
Revises: a6df9286ae8b
Create Date: 2026-02-21 14:16:52.945306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15c85a88b1c2'
down_revision: Union[str, Sequence[str], None] = 'a6df9286ae8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflect--goal_version',
    sa.Column('id', sa.String(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(), autoincrement=False, nullable=True),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', name='goalpriority'), autoincrement=False, nullable=True),
    sa.Column('exit_criteria', sa.String(), autoincrement=False, nullable=True),
    sa.Column('action_plan', sa.String(), autoincrement=False, nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PIVOTED', 'ARCHIVED', name='goalstatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('month_created', sa.String(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.Column('title_mod', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('priority_mod', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('exit_criteria_mod', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('action_plan_mod', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('status_mod', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at_mod', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('month_created_mod', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_reflect--goal_version_end_transaction_id'), 'reflect--goal_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_reflect--goal_version_operation_type'), 'reflect--goal_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_reflect--goal_version_transaction_id'), 'reflect--goal_version', ['transaction_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('remote_addr', sa.String(length=50), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction')
    op.drop_index(op.f('ix_reflect--goal_version_transaction_id'), table_name='reflect--goal_version')
    op.drop_index(op.f('ix_reflect--goal_version_operation_type'), table_name='reflect--goal_version')
    op.drop_index(op.f('ix_reflect--goal_version_end_transaction_id'), table_name='reflect--goal_version')
    op.drop_table('reflect--goal_version')
    # ### end Alembic commands ###
