"""add reflect models for goal tracking

Revision ID: b6bb6e680abe
Revises: 414aabd576eb
Create Date: 2026-02-12 10:30:55.239987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6bb6e680abe'
down_revision: Union[str, Sequence[str], None] = '414aabd576eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflect--goal',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('priority', sa.Enum('P1', 'P2', 'P3', name='goalpriority'), nullable=False),
    sa.Column('exit_criteria', sa.String(), nullable=False),
    sa.Column('action_plan', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PIVOTED', 'ARCHIVED', name='goalstatus'), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('month_created', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflect--monthly_review',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('key_takeaway', sa.String(), nullable=False),
    sa.Column('finalized_at', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflect--goal_month_outcome',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('outcome', sa.Enum('COMPLETED', 'IN_PROGRESS', 'PIVOTED', name='goaloutcome'), nullable=False),
    sa.Column('reflection_note', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['reflect--goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflect--scratchpad_note',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('promoted_to_goal_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['promoted_to_goal_id'], ['reflect--goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reflect--weekly_check_in',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('goal_id', sa.String(), nullable=False),
    sa.Column('week_of', sa.String(), nullable=False),
    sa.Column('tracking_status', sa.Enum('ON_TRACK', 'AT_RISK', 'OFF_TRACK', name='trackingstatus'), nullable=False),
    sa.Column('reflection_note', sa.String(), nullable=False),
    sa.Column('strategy_adjustment', sa.String(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['goal_id'], ['reflect--goal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('second_thought--justification')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('second_thought--justification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('ts', sa.DATETIME(), nullable=False),
    sa.Column('domain', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('reason', sa.VARCHAR(), nullable=False),
    sa.Column('duration', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reflect--weekly_check_in')
    op.drop_table('reflect--scratchpad_note')
    op.drop_table('reflect--goal_month_outcome')
    op.drop_table('reflect--monthly_review')
    op.drop_table('reflect--goal')
    # ### end Alembic commands ###
